# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\edu.local\public\studenthomes\22200322\Desktop\bebra\design\edit_data_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(57, 208, 208);\n"
"    border-radius: 31px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(50, 20, 301, 51))
        self.name_input.setObjectName("name_input")
        self.price_input = QtWidgets.QLineEdit(self.centralwidget)
        self.price_input.setGeometry(QtCore.QRect(50, 80, 301, 51))
        self.price_input.setObjectName("price_input")
        self.count_input = QtWidgets.QLineEdit(self.centralwidget)
        self.count_input.setGeometry(QtCore.QRect(50, 140, 301, 51))
        self.count_input.setObjectName("count_input")
        self.path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.path_input.setGeometry(QtCore.QRect(50, 200, 301, 51))
        self.path_input.setObjectName("path_input")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Изменить"))
        self.name_input.setPlaceholderText(_translate("MainWindow", "Введите новое имя товара"))
        self.price_input.setPlaceholderText(_translate("MainWindow", "Введите цену товара"))
        self.count_input.setPlaceholderText(_translate("MainWindow", "Введите количество товара"))
        self.path_input.setPlaceholderText(_translate("MainWindow", "Введите путь изображения"))
