# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\edu.local\public\studenthomes\22200322\Desktop\db_2\design\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftTable = QtWidgets.QTableView(self.centralwidget)
        self.leftTable.setGeometry(QtCore.QRect(10, 10, 431, 471))
        self.leftTable.setObjectName("leftTable")
        self.rightTable = QtWidgets.QTableView(self.centralwidget)
        self.rightTable.setGeometry(QtCore.QRect(590, 10, 431, 471))
        self.rightTable.setObjectName("rightTable")
        self.send_to_right = QtWidgets.QPushButton(self.centralwidget)
        self.send_to_right.setGeometry(QtCore.QRect(470, 100, 91, 81))
        self.send_to_right.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.send_to_right.setObjectName("send_to_right")
        self.send_to_left = QtWidgets.QPushButton(self.centralwidget)
        self.send_to_left.setGeometry(QtCore.QRect(470, 260, 91, 81))
        self.send_to_left.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.send_to_left.setObjectName("send_to_left")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(280, 500, 511, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 0, 2, 1)
        self.delButton_l = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton_l.sizePolicy().hasHeightForWidth())
        self.delButton_l.setSizePolicy(sizePolicy)
        self.delButton_l.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.delButton_l.setObjectName("delButton_l")
        self.gridLayout.addWidget(self.delButton_l, 0, 2, 1, 1)
        self.editButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        self.editButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 0, 4, 2, 1)
        self.delButton_r = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delButton_r.sizePolicy().hasHeightForWidth())
        self.delButton_r.setSizePolicy(sizePolicy)
        self.delButton_r.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    ;\n"
"    background-color: rgb(49, 223, 211);\n"
"    border-radius: 31px;\n"
"}")
        self.delButton_r.setObjectName("delButton_r")
        self.gridLayout.addWidget(self.delButton_r, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_to_right.setText(_translate("MainWindow", "=>"))
        self.send_to_left.setText(_translate("MainWindow", "<="))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.delButton_l.setText(_translate("MainWindow", "Удалить(Левая)"))
        self.editButton.setText(_translate("MainWindow", "Редактировать"))
        self.delButton_r.setText(_translate("MainWindow", "Удалить(Правая)"))
